name: Replace string in file

on:
  push:
    branches:
      - PROD

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flcdrg/replace-multiple-action@v1
        with:
          files: '**'
          find: '[{ "find": "KUIPER_DEV", "replace": "KUIPER" }]'